/*
    A] MR. ABC YOU HIRED ON DEF IN DEPTNO GHI
*/
    SELECT 'MR.' || ENAME || ' YOU ARE HIRED ON ' || HIREDATE || ' IN DEPTNO ' || DEPTNO AS "HIRED IN"
    FROM SCOTT.EMP ;

/*
    B] HEY! ABC YOUR WORKIN AS DEF IN DEPTNO GHI
*/
    SELECT ' HEY! ' || ENAME || ' YOUR WORKING AS ' || JOB || ' IN DEPTNO ' || DEPTNO  AS "WORKING AS"
    FROM SCOTT.EMP;

/*
    C] OYE! XYZ YOUR SALARY IS RS. ABS AND COMMISSION IS GKL
*/
    SELECT ' OYE! ' || ENAME || ' YOUR SALARY IS RS. ' || SAL || ' AND COMMISSION IS ' || COMM  AS "SALARY AND COMMITION"
    FROM SCOTT.EMP;

/*
    D] HEY DONKEY! WORK MORE AND GIVE ME YOUR ANNUAL SALARY IN ONE SHORT THAT IS FGH
*/
    SELECT 'HEY DONKEY! WORK MORE AND GIVE ME YOUR ANNUAL SALARY IN ONE SHORT THAT IS ' || SAL*12 AS "ANNUAL SALARY"
    FROM SCOTT.EMP;

/*
    E] SORRY! ABC YOUR SAL IS RS.GHK AND WE ARE DEDUCTING 100 RPS IN IT FOR THAT YOU WILL GET JUST RTY
*/
    SELECT 'SORRY!' || ENAME || 'YOUR SAL IS RS ' || SAL || ' AND WE ARE DEDUCTING 100 RPS IN IT FOR THAT YOU WILL GET JUST ' || (SAL-100)  AS  "SALARY DEDUCTION"
    FROM SCOTT.EMP;


/*
    F] HI! ABC YOUR DESIGNATION IS KLO THAT TOO IN DEPTNO TYU
*/
    SELECT 'HI!' || ENAME || 'YOUR DESIGNATION IS' || JOB || 'THAT TOO IN DEPTNO' || DEPTNO AS "DESIGNATION"
    FROM SCOTT.EMP;

/*
    G] HELLO! QWE YOUR EMP ID IS ERT AND MANAGER ID IS JUI
*/
    SELECT 'HELLO!' || ENAME || 'YOUR EMP ID IS' || EMPNO || 'AND MANAGER ID IS' || MGR AS "ID'S"
    FROM SCOTT.EMP;

/*
    H] ABC IS VERY KIND HEARTED WE NEED TO APPRECIATE THAT
*/
    SELECT ENAME || 'IS VERY KIND HEARTED WE NEED TO APPRECIATE THAT'
    FROM SCOTT.EMP ;

/*
    I] MR. ABC YOUR SALARY IS RS.QWE AND HALFTERM IS RS.HJK
*/
    SELECT 'MR. ABC YOUR SALARY IS RS.' || SAL || 'AND HALFTERM IS RS.' || SAL*6
    FROM SCOTT.EMP;

/*
    J] HEY! AVG YOUR SALARY IS RS.UIO AND YOU GOT 3000 RPS HIKE SO YOU WILL GET RS.TYU
*/
    SELECT ' HEY!' || ENAME || 'YOUR SALARY IS RS.' || SAL || 'AND YOU GOT 3000 RPS HIKE SO YOU WILL GET RS.' || (SAL+3000) AS " SALARY HIKE"
    FROM SCOTT.EMP;

