/*
    1] WAQTD TOTAL SAL GIVEN TO EACH EMP(SAL+COMM)..
*/
        SELECT SAL+COMM AS "TOTAL SALARY"
        FROM SCOTT.EMP;

/*
    2] WAQTD ALL THE DETAILS OF EMP ALONG WITH ANNUAL SAL...
*/
        SELECT EMP .* , SAL*12 AS "ANNUAL SALARY"
        FROM SCOTT.EMP;

/*
    3] WAQTD ALL THE DETAILS OF EMP ALONG WITH ANNUAL BONUS OF 2000....
*/
        SELECT EMP .*, SAL*12+2000 AS "ANNUAL BONUS"
        FROM SCOTT.EMP;

/*
    4] WAQTD ALL THE DETAILS OF EMP ALONG WITH SAL HIKE OF 50RPS..
*/
        SELECT EMP .* , SAL+50 AS  "50RS_HIKE"
        FROM SCOTT.EMP;

/*
    5] WAQTD ALL THE DETAILS OF EMP ALONG WITH DEDUCTION OF 50 IN SAL...
*/
        SELECT EMP .* , SAL-50 SALARY_DEDUCED 
        FROM SCOTT.EMP;

/*
    6] WAQTD ALL THE DETAILS ABOUT EMPLOYEE AND HIS 2 MONTHS SAL..
*/
        SELECT EMP .* , SAL*2 AS "2_MO_SAL"
        FROM SCOTT EMP;

/*
    7] WAQTD ALL THE DETAILS OF EMP ALONG WITH DEDUCTION OF 25% IN THERE ANNUAL SAL..
*/
        SELECT EMP .*, SAL-SAL*25/100 AS "25% DEDUCTION"
        FROM SCOTT.EMP;

/*
    8] WAQTD ALL THE DETAILS OF EMP ALONG WITH HIKE OF 33% IN HIS MONTHLY SAL..
*/
        SELECT EMP .*, SAL+SAL*33/100 AS "33% HIKE"
        FROM SCOTT.EMP;

/*
    9] WAQTD ALL DETAILS OF EMP ALONG WITH HIKE OF 35% IN THERE ANNUAL SAL..
*/
        SELECT EMP .* , SAL+SAL*35/100
        FROM SCOTT.EMP;

/*
    10] WAQTD ALL DETAILS OF EMP ALONG WITH DEDUCTION OF 500 IN THERE 5 MONTHS SAL..
*/
        SELECT EMP .*, SAL*5-500
        FROM SCOTT.EMP;

/*
    11] WAQTD ALL DETAILS OF EMP ALONG WITH 28% OF HIKE IN THE SAL & 33% DEDUCTION IN HIS HALF TERM SAL& 45% HIKE IN HIS ANNUAL SAL...
*/
        SELECT EMP .*, SAL+SAL*28/100,  SAL*6-SAL*6*33/100, SAL*12+SAL*12*45/100
        FROM SCOTT.EMP;

/*
    12] WAQTD ALL THE DETAILS OF EMP ALONG WITH 45% DEDUCTION IN THE SALARY FOR ALL THE EMP’S.
*/
        SELECT EMP .* , SAL*SAL-45/100
        FROM SCOTT.EMP;

/*
    13] WAQTD NAME, SALARY, 4 MONTHS SALARY, 32% HIKE IN THE 4 MONTHS SALARY FOR ALL THE EMP’S.
*/
        SELECT ENAME, SAL, SAL*4, SAL*4*32/100
        FROM SCOTT.EMP;

/*
    14] WAQTD NAME, SALARY, 9 MONTHS SALARY, 12.34% DEDUCTION IN THE 9 MONTHS SALARY FOR ALL THE EMP’S.
*/
        SELECT ENAME, SAL, SAL*9, SAL*9-SAL*9-12.34/100
        FROM SCOTT.EMP;

/*
    15] WAQTD ALL THE DETAILS ALONG WITH HALF_TERM SALARY, ANNUAL_SALARY, TOTAL SALARY FOR ALL THE EMP’S.
*/
        SELECT EMP .*, SAL*6, SAL*12, SAL*12 AS TOTAL_SAL
        FROM SCOTT.EMP;