
SELECT ENAME 
FROM SCOTT.EMP
WHERE ENAME LIKE 'A%' OR
      ENAME LIKE 'E%' OR
      ENAME LIKE 'I%' OR
      ENAME LIKE 'O%' OR
      ENAME LIKE 'U%' ;


SELECT ENAME 
FROM SCOTT.EMP
WHERE ENAME NOT LIKE 'A%' OR
      ENAME NOT LIKE 'E%' OR
      ENAME NOT LIKE 'I%' OR
      ENAME NOT LIKE 'O%' OR
      ENAME NOT LIKE 'U%' ;

SELECT ENAME 
FROM SCOTT.EMP
WHERE ENAME LIKE '%A' OR
      ENAME LIKE '%E' OR
      ENAME LIKE '%I' OR
      ENAME LIKE '%O' OR
      ENAME LIKE '%U' ;


SELECT ENAME 
FROM SCOTT.EMP
WHERE ENAME NOT LIKE '%A' OR
      ENAME NOT LIKE '%E' OR
      ENAME NOT LIKE '%I' OR
      ENAME NOT LIKE '%O' OR
      ENAME NOT LIKE '%U' ;

SELECT ENAME
FROM SCOTT.EMP
WHERE ENAME LIKE '__A%' OR
      ENAME LIKE '__E%' OR
      ENAME LIKE '__I%' OR
      ENAME LIKE '__O%' OR
      ENAME LIKE '__U%' ;


SELECT ENAME
FROM SCOTT.EMP
WHERE ENAME NOT LIKE '%A___' OR
      ENAME NOT LIKE '%E___' OR
      ENAME NOT LIKE '%I___' OR
      ENAME NOT LIKE '%O___' OR
      ENAME NOT LIKE '%U___' ;


SELECT ENAME
FROM SCOTT.EMP
WHERE ENAME LIKE '%A%';


SELECT ENAME 
FROM SCOTT.EMP
WHERE ENAME LIKE '%A%' AND
      ENAME NOT LIKE '%A%A%' ;

SELECT ENAME 
FROM SCOTT.EMP
WHERE ENAME LIKE '%A%A%' ;

SELECT ENAME
FROM SCOTT.EMP
WHERE ENAME LIKE '%A%A%' AND
      ENAME NOT LIKE '%A%A%A%' ;

SELECT ENAME 
FROM SCOTT.EMP
WHERE ENAME LIKE '%L%' AND
      ENAME NOT LIKE '%L%L%' ;

SELECT ENAME 
FROM SCOTT.EMP
WHERE ENAME LIKE '%T%' AND
      ENAME NOT LIKE '%T%T%' ;

SELECT ENAME
FROM SCOTT.EMP
WHERE ENAME LIKE '%L%L%' AND
      ENAME NOT LIKE '%L%L%L%' ;













