/*
    1] WAQTD DIFFERENT SALARY & DEPINTO WITH 21% DEDUCTION IN THE SALARY IN EMP TABLE IF 21% DEDUCTION IS MORE THAN 2000 RPS.
*/
            SELECT DISTINCT SAL, DEPTNO, SAL-SAL*21/100 AS "21%DEDUCTION"
            FROM SCOTT.EMP 
            WHERE SAL > 2000;

/*
    2] WAQTD ALL THE DETAILS & HALF TERM SALARY FOR THE EMP’S IF THE EMP IS EARNING AT LEAST 1250 RPS IN THE DEPTNO 10 OR 30 WITH HIRE DATE AFTER 3/12/1981.
*/
            SELECT EMP .* , SAL*6 AS "HALFTERM SAL"
            FROM SCOTT.EMP
            WHERE SAL >= 1250 AND
                  DEPTNO IN (10, 30) AND 
                  HIREDATE > '03-DEC-1981' ;

/*
    3] WAQTD NAMES OF EMP’S WHO HIRED AFTER 1975 BUT BEFORE 1985 EXCEPT THE YEAR 1982 & WORKING AS ‘CLERK’ OR ‘ANALYST’ OR ‘PRESIDENT’ EXCEPT THE DEPTNO 20.
*/
            SELECT ENAME
            FROM SCOTT.EMP
            WHERE HIREDATE > '31-DEC-1975' AND
                  HIREDATE < '01-JAN-1985' AND
                  HIREDATE NOT BETWEEN '01-JAN-1982' AND
                                        '31-DEC-1982' AND
                  JOB IN ('CLERK' , 'ANALYST' , 'PRESIDENT') AND
                  DEPTNO != 20;
                                
/*
4] WAQTD DETAILS OF EMP’S IF EMP IS HAVING CHAR ‘A’ IN THE NAME BUT NOT ‘S’. WITH EARNING ATMOST 3000 RPS WAGES WITHOUT HAVING MANAGER NO 7566,7839.
*/
            SELECT *
            FROM SCOTT.EMP
            WHERE ENAME LIKE '%A%' AND
                  ENAME NOT LIKE '%S%' AND
                  SAL <= 3000 AND
                  MGR NOT IN (7566, 7839);

/*
    5] WAQTD NAMES OF EMP’S IF EMP IS HIRED IN THE YEAR 1981 EXCEPT THE MONTHS FEB & MAY, WITH THE 4 DIGIT SALARY & STRING ‘AN’ IN THE DESIGNATION & EMP SHOULD BE HAVING COMMISSION.
*/
            SELECT ENAME 
            FROM SCOTT.EMP
            WHERE HIREDATE BETWEEN '01-JAN-1981' AND
                                    '31-DEC-1981' AND
                  HIREDATE NOT BETWEEN '01-FEB-1981' AND
                                        '28-FEB-1981' AND
                  HIREDATE NOT BETWEEN '01-MAY-1981' AND
                                        '31-MAY-1981' AND
                  SAL LIKE '____' AND
                  JOB LIKE '%AN%' AND
                  COMM IS NOT NULL;

/*
    6] WAQTD THE O/P IN THE FOLLOWING FORMAT.
    HEY! ABC YOU ARE EARNING RPS.XYZ WITH HIKE OF 35% KGF
    [IF EMP IS EARNING THE SALARY WITH THE RANGE 1250 TO 1600 WITH HAVING MANAGER NUMBER].
            
*/
            SELECT 'HEY!' || ENAME || 'YOU ARE EARNING RPS. ' || SAL || 'WITH THE HIKE OF 35% ' || (SAL+SAL*35/100) 
            FROM SCOTT.EMP 
            WHERE SAL BETWEEN 1250 AND 1600 
           AND MGR IS NOT NULL;
/*
    7] WAQTD NAMES OF EMP’S WHOSE DESIGNATION STARTS WITH EITHER ‘C’ OR ‘S’ WITH AT LEAST 1000 RPS WAGES WITHOUT COMMISSION.
*/
            SELECT ENAME
            FROM SCOTT.EMP
            WHERE JOB LIKE 'C%' OR
                  JOB LIKE 'S%' AND 
                  SAL >= 1000 AND
                  COMM IS NULL;


/*
    8] WAQTD EMP NAME, JOINING DATE & DEPTNO IF EMP’S NAME IS HAVING ‘N’ AS 2ND LAST CHAR & ‘I’ AT 2ND PLACE WITH HIRED MONTH OF NOVEMBER & SHOULD WORK EITHER IN THE DEPTNO 10 OR 30 EXCEPT ‘22-NOV-82’ & ‘17-NOV-87’ WITHOUT HAVING MANAGER NUMBER.
*/
            SELECT ENAME, HIREDATE, DEPTNO
            FROM SCOTT.EMP
            WHERE ENAME LIKE '%N_' AND
                  ENAME LIKE '_I%' AND
                  HIREDATE LIKE '%NOV%' AND
                  DEPTNO IN (10,30) AND 
                  HIREDATE NOT IN ('22-NOV-82' , '17-NOV-87') AND 
                  MGR IS NULL;
/*
9] WAQTD NAME, DESIGNATION & COMMISSION OF EMP’S WHO ARE EARNING COMMISSION WITH HAVING STRING ‘LES’ IN THE DESIGNATION & THAT COMMISSION SHOULD BE 3 DIGIT OR 1 DIGIT ONLY.
*/
            SELECT ENAME, JOB,COMM
            FROM SCOTT.EMP
            WHERE COMM IS NOT NULL AND
                  JOB LIKE '%LES%' AND
                  COMM LIKE '___' OR
                  COMM LIKE '_' ;

/*
    10] WAQTD THE O/P IN THE FOLLOWING FORMAT.
    DEAR! ABC YOU ARE WORKING AS A XYZ AND HIRED ON PQR WITH THE SALARY IN HAND ORF.
    (IF EMP’S HALF_TERM SALARY IS LESS THAN 10K WITH NAME HAVING 4TH LAST CHAR 'R'
*/
            SELECT 'DEAR!' || ENAME || 'YOU ARE WORKING AS ' || JOB || 'AND HIRED ON ' || JOB || 'WITH THE SALARY IN HAND ' || SAL
            FROM SCOTT.EMP
            WHERE SAL*6 < 10000 AND
                  ENAME LIKE '%R___';

