/*
    1] WAQTD EMPLOYEE NAME, SAL OF ALL THE EMPLOYEES.
*/

        SELECT ENAME, SAL
        FROM SCOTT.EMP;

/*
    2] WAQTD JOB & SALARY OF ALL THE EMPLOYEES.
*/
        SELECT JOB, SAL
        FROM SCOTT.EMP;

/*
    3] WAQTD NAME & JOB OF ALL EMPLOYEES.
*/
        SELECT ENAME,JOB
        FROM SCOTT.EMP;

/*
    4] WAQTD ALL THE DETAILS FROM EMP TABLE.
*/
        SELECT * FROM SCOTT.EMP;

/*
    5] WAQTD THE TABLES PRESENT IN THE DATABASE.
*/
       SELECT * FROM TAB; 

/*
    6] WAQTD EMPLOYEE ID & DEPARTMENT NO OF ALL THE EMP'S.
*/
        SELECT EMPNO, DEPTNO
        FROM SCOTT.EMP;

/*
    7] WAQTD EMP NAME & HIREDATE OF ALL EMP'S.
*/
        SELECT ENAME,HIREDATE
        FROM SCOTT.EMP;

/*
    8] WAQTD NAME & DESIGNATION OF ALL EMP'S.
*/
        SELECT ENAME, JOB
        FROM SCOTT.EMP;

/*
    9] WAQTD NAME & ANNUAL SALARY OF ALL THE EMP'S.
*/
        SELECT ENAME, SAL*12 AS ANNUAL_SALARY
        FROM SCOTT.EMP;

/*
    10] WAQTD NAME & HALF-TERM SALARY OF ALL THE EMP'S.
*/
        SELECT ENAME, SAL * 6 AS HALFTERM_SAL
        FROM SCOTT.EMP;

/*
    11] WAQTD NAME, SALARY & SALARY WITH 25% HIKE.
*/
        SELECT ENAME, SAL, SAL+SAL*25/100 AS "25%HIKE"
        FROM SCOTT.EMP;

/*
    12] WAQTD NAME, SALARY & SALARY WITH 25% DEDUCTION.
*/
        SELECT ENAME, SAL, SAL-SAL*25/100 AS "25%DEDUCTION"
        FROM SCOTT.EMP;

/*
    13] WAQTD NAME, SALARY & SAL WITH 12% DEDUCTION.
*/

        SELECT ENAME, SAL, SAL- SAL*12/100 AS "12%DEDUCTION"
        FROM SCOTT.EMP;

/*
    14] WAQTD NAME, SALARY & SAL WITH 18% HIKE.
*/
        SELECT ENAME, SAL, SAL+SAL*18/100
        FROM SCOTT.EMP;

/*
    15] WAQTD NAME, SALARY & SAL WITH 40% DEDUCTION.
*/
        SELECT ENAME, SAL, SAL-SAL*40/100
        FROM SCOTT.EMP;

/*
    16] WAQTD NAME, SALARY & SAL WITH 7% HIKE.
*/
        SELECT ENAME, SAL, SAL+SAL*7/100
        FROM SCOTT.EMP;

/*
    17] WAQTD NAME, SALARY & SAL WITH 5000 BONUS.
*/
        SELECT ENAME, SAL, SAL+5000
        FROM SCOTT.EMP;

/*
    18] WAQTD NAME, SALARY, HALF TERM SAL & 4500 BONUS IN HALF-TERM SALARY.
*/
        SELECT ENAME, SAL, SAL/2, SAL/2+4500 AS "HALF TERM BONUS"
        FROM SCOTT.EMP;

/*
    19 WAQTD NAME, SALARY, ANNUAL SAL & 7800 BONUS IN ANNUAL SALARY.
*/
        SELECT ENAME, SAL, SAL*12, SAL*12+7800
        FROM SCOTT.EMP;

/*
    20] WAQTD NAME, ANNUAL SAL & SALARY WITH 34% HIKE.
*/
        SELECT ENAME, SAL*12, SAL*12+SAL*12*34/100
        FROM SCOTT.EMP;

/*
    21] WAQTD NAME, SAL, HALF-TERM SALARY WITH 5% HIKE, ANNUAL SALARY WITH 23% DEDUCTION.
*/
        SELECT ENAME, SAL, SAL/2, SAL/2+SAL/2*5/100, SAL*12- SAL*12*23/100
        FROM SCOTT.EMP;

/*
    22] WAQTD JOB, HIREDATE, DEPTNO, SAL, SAL WITH 4300 BONUS, HAL-TERM SAL WITH 3790 BONUS.
*/
        SELECT JOB, HIREDATE,DEPTNO, SAL, SAL+4300, SAL/2+3790
        FROM SCOTT.EMP;

/*
    23] WAQTD NAME, SAL, SAL WITH 3400 HIKE & ANUAL SAL WITH 5768 HIKE.
*/

        SELECT ENAME,SAL,SAL+3400, SAL*12+5768
        FROM SCOTT.EMP;

/*
    24] WAQTD NAME, SALARY, SAL ALONG WITH 58% DEDUCTION & 4500 BONUS IN HALTERM SAL.
*/
        SELECT ENAME, SAL, SAL-SAL*58/100, SAL*6+4500
        FROM SCOTT.EMP;

/*
    25] WAQTD TOTAL SALARY OF ALL THE EMPLOYEES.
*/
        SELECT SUM(SAL) FROM SCOTT.EMP;

/*
    26] WAQTD TOTAL SALARY & 3400 DEDUCTION IN HALF-TERM SAL
*/
        SELECT SUM(SAL), (SUM(SAL)*6)-3400
        FROM SCOTT.EMP;