/*
    1] WAQTD DETAILS OF SMITH.
*/

        SELECT SCOTT.EMP .*
        FROM SCOTT.EMP
        WHERE ENAME = 'SMITH' ;

/*
    2] WAQTD DESIGNATION OF ALLEN.
*/
        SELECT JOB
        FROM SCOTT.EMP
        WHERE ENAME = 'ALLEN' ;

/*
    3] WAQTD SALARY OF SCOTT.
*/
        SELECT SAL
        FROM SCOTT.EMP
        WHERE ENAME = 'SCOTT';

/*
    4] WAQTD MILLER'S HIREDATE.
*/
        SELECT HIREDATE
        FROM SCOTT.EMP
        WHERE ENAME = 'MILLER' ;

/*
    5] WAQTD DEPTTNO OF MARTIN.
*/
        SELECT DEPTNO
        FROM SCOTT.EMP
        WHERE ENAME = 'MARTIN' ;

/*
    6] WAQTD NAMES OF AN EMP WORKING AS SALESMAN.
*/
        SELECT ENAME
        FROM SCOTT.EMP
        WHERE JOB = 'SALESMAN';

/*
    7] WAQTD ALL THE DETAILS OF EMP WORKING AS MANAGER.
*/
        SELECT EMP .*
        FROM SCOTT.EMP
        WHERE JOB = 'MANAGER';
/*
    8] WAQTD NAME,JOB,SALARY, & HIREDATE OF PRESIDENT.
*/
        SELECT ENAME, JOB, SAL, HIREDATE
        FROM SCOTT.EMP
        WHERE JOB = 'PRESIDENT' ;

/*
    9] WAQTD NAMES OF AN EMP WORKING IN DEPTNO 20.
*/
        SELECT ENAME
        FROM SCOTT.EMP
        WHERE DEPTNO = 20;

/*
    10] WAQTD NAMES OF AN EMP EARNING 1250RPS.
*/
        SELECT ENAME
        FROM SCOTT.EMP
        WHERE SAL = 1250;
/*
    11] WAQTD NAMES OF AN EMP EARNING COMMISSION OF 500RPS.
*/
        SELECT ENAME
        FROM SCOTT.EMP
        WHERE COMM = 500;

/*
    12] WAQTD NAME, SAL, ANNUAL SAL OF EMP'S WORKING IN DEPTNO 30.
*/
        SELECT ENAME, SAL, SAL*12 AS "ANNUAL SALARY"
        FROM SCOTT.EMP
        WHERE DEPTNO = 30;

/*
    13] WAQTD DETAILS OF AN EMP EARNING MORE THAN 2000 RPS.
*/
        SELECT EMP .* 
        FROM SCOTT.EMP
        WHERE SAL > 2000 ;

/*
    14] WAQTD DETAILS OF AN EMP EARNING LESS THAN 3000 RPS.
*/
        SELECT EMP .*
        FROM SCOTT.EMP
        WHERE SAL < 3000;

/*
    15] WAQTD NAMES OF AN EMP EARNING COMMISSION MORE THAN 500.
*/
        SELECT ENAME
        FROM SCOTT.EMP
        WHERE COMM > 500;

/*
    16] WAQTD DETAILS OF AN EMP HIRED AFTER 1981.
*/
        SELECT EMP .*
        FROM SCOTT.EMP
        WHERE HIREDATE > '1981';