/*
    1] WAQTD DETAILS OF AN EMP HIRED BEFORE 1987.
*/

        SELECT *
        FROM SCOTT.EMP
        WHERE HIREDATE < '01-JAN-1986' ;

/*
    2] WAQTD NAMES OF AN EMP WORKING AS A CLERK & EARNING LESS THAN 1000.
*/
        SELECT ENAME
        FROM SCOTT.EMP
        WHERE JOB = 'CLERK' AND
              SAL < 1000;

/*
    3] WAQTD NAMES OF AN EMP WORKING AS SALESMAN IN DEPTNO 20.
*/
        SELECT ENAME
        FROM SCOTT.EMP
        WHERE JOB = 'SALESMAN' AND
              DEPTNO = 20;

/*
    4] WAQTD SALARY OF PRESIDENT.
*/
        SELECT SAL
        FROM SCOTT.EMP
        WHERE JOB = 'PRESIDENT' ;

/*
    5] WAQTD NAMES OF AN EMP WORKING AS ANALYST.
*/
        SELECT ENAME
        FROM SCOTT.EMP
        WHERE JOB = 'ANALYST' ;

/*
    6] WAQTD NAMES OF AN EMP EARNING LESS THAN 1000.
*/
        SELECT ENAME
        FROM SCOTT.EMP
        WHERE SAL < 1000;

/*
    7] WAQTD NAMES OF AN EMP EARNING RS.3000.
*/
        SELECT ENAME
        FROM SCOTT.EMP
        WHERE SAL = 3000;

/*
    8] WAQTD DETAILS OF AN EMP HIRED BEFORE 1981.44
*/

/*
    9] WAQTD NAMES OF AN EMP HIRED AFTER 1982.
*/
        SELECT ENAME 
        FROM SCOTT.EMP
        WHERE HIREDATE > '31-DEC-1981' ;

/*
    10] WAQTD NAMES OF AN EMP EARNING COMMISSION LESS THAN 300.
*/
        SELECT ENAME
        FROM SCOTT.EMP
        WHERE COMM < 300;

/*
    11] WAQTD NAMES OF AN EMP WORKING IN DEPTNO 10.
*/
        SELECT ENAME
        FROM SCOTT.EMP
        WHERE DEPTNO = 10;

/*
    12] WAQTD NAMES OF AN EMP WORKING AS A CLERK & EARNING MORE THAN 1000.
*/
        SELECT ENAME
        FROM SCOTT.EMP
        WHERE JOB = 'CLERK' AND
              SAL >1000;

/*
    13] WAQTD DETAILS OF AN EMP WORKING AS MANAGER IN DEPTNO 20.
*/
        SELECT *
        FROM SCOTT.EMP
        WHERE JOB ='MANAGER' AND
              DEPTNO = 20;

/*
    14] WAQTD DETAILS OF AN EMP WORKING AS CLERK & HIRED AFTER 1980.
*/
        SELECT *
        FROM SCOTT.EMP
        WHERE JOB ='CLERK' AND
              HIREDATE > '01-JAN-1981';
/*
    15] WAQTD DETAILS OF AN EMP WORKING AS AN ANALYST & HIRED AFTER 1981.
*/
        SELECT *
        FROM SCOTT.EMP
        WHERE JOB = 'ANALYST' AND
              HIREDATE > '01-JAN-1982' ;

/*
    16] WAQTD DETAILS OF AN EMP WORKING AS A SALESMAN IN DEPTNO 30 & EARNING MORE THAN 1500.
*/
        SELECT *
        FROM SCOTT.EMP
        WHERE JOB = 'SALESMAN' AND
              DEPTNO = 30 AND
              SAL > 1500 ;

/*
    17] WAQTD DETAILS OF AN EMP WORKING AS CLERK IN DEOTNO 20 & HIRED AFTER 1980.
*/
        SELECT *
        FROM SCOTT.EMP
        WHERE JOB ='CLERK' AND
              DEPTNO = 20 AND
              HIREDATE > '01-JAN-1981' ;

/*
    18] WAQTD DETAILS OF AN EMP WORKING AS PRESIDENT OR ANALYST.
*/
        SELECT * 
        FROM SCOTT.EMP
        WHERE JOB = 'PRESIDENT' OR
              JOB = 'ANALYST' ;

/*
    19] WAQTD DETAILS OF AN EMP WHO ARE EARNING MORE THAN 2500 & LESS THAN 3000.
*/
        SELECT *
        FROM SCOTT.EMP
        WHERE SAL > 2500 AND
              SAL <3000 ;

/*
    20] WAQTD DETAILS OF AN EMP HIRED AFTER 1981 & BEFORE 1987.
*/
        SELECT *
        FROM SCOTT.EMP
        WHERE JOB > '31-DEC-1982' AND
              JOB < '01-JAN-1986' ;

/*
    21] WAQTD DETAILS OF AN EMP WORKING AS MANAGER & HIRED AFTER 1981.
*/
        SELECT SCOTT.EMP .*
        FROM SCOTT.EMP 
        WHERE HIREDATE = '01-JAN-1987' ;

/*
    22] WAQTD DETAILS OF AN EMP HIRED IN THE YEAR 1987.
*/

        SELECT SCOTT.EMP .* 
        FROM SCOTT.EMP
        WHERE HIREDATE > '31-DEC-1980' AND
              HIREDATE < '01-JAN-1980' ;

/*
    23] WAQTD DETAILS OF AN EMP WORKING AS PRESIDENT OR HIRED BEFORE 1981.
*/

        SELECT EMP .*
        FROM EMP
        WHERE JOB = 'PRESIDENT' AND 
              HIREDATE < '01-JAN-1981' ;

/*
    24] WAQTD DETAILS OF AN EMP WORKING IN DEPTNO 10 OR 20.
*/
        SELECT SCOTT.EMP .*
        FROM SCOTT.EMP 
        WHERE DEPTNO = 10
        OR DEPTNO = 30;

/*
    25] WAQTD DETAILS OF AN EMP WORKING IN DEPTNO 20 OR 30.
*/
        SELECT SCOTT.EMP .*
        FROM SCOTT.EMP
        WHERE DEPTNO = 20 OR
        DEPTNO = 30;